### PR TITLE
Fire dataChange after validation is finished

### LINKED ISSUE #238: Form fires dataChange event before validation is finished
This causes issues in the questionnaire where the autosave skips saving if the fieldState is not yet $valid
### How to Reproduce
Nontrivial without adding extra logging but what works for me:
* Open the unique string demo
* Open the vue debugger, tab Components, select the VueForm for the demo, open the state prop
* now watch both the data.uniqueExample value and the $pending value in the state and type a single letter in the field

### Expected behavior
the data value is updated when $pending is false

### Observed behavior
the data value is updated while $pending is still true

### PR DESCRIPTION
**Pull request by fdlk**
Fixes #238

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/integration/system tested
- [x] User documentation updated
- [x] Clean commits
- [x] No warnings during install
- [x] Updated flow typing

### CODE REVIEW

File: src/components/field-types/RadioFieldComponent.vue [hunk 1]
```diff
@@ -1,5 +1,5 @@
 <template>
-  <validate :state="fieldState" :custom="{'validate': isValid, 'unique': isUnique}" v-if="options.length > 0">
+  <validate :state="fieldState" :custom="{'validate': isValid, 'unique': isUnique}" v-if="options.length > 0" :debounce="1">
```
Comment (ConnorStroomberg) [inline src/components/field-types/RadioFieldComponent.vue]: maybe add a note about the magic '1' , on why it is there or use a named constant

File: src/components/FormFieldComponent.vue [hunk 2]
```diff
@@ -261,6 +258,13 @@
         return defaultNoOptionsMessage
       }
     },
+    watch: {
+      pending (isPending) {
+        if (!isPending) {
```
Comment (ConnorStroomberg) [inline src/components/FormFieldComponent.vue]: maybe add note that were actually watching for the flip of pending, this is not directly apparent when looking at the code i think
