### PR TITLE
fix: Put a non-breaking space between label and asterisk

### LINKED ISSUE #244: Asterisk for required form sometimes ends up on separate line
### How to Reproduce
Resize window with required question with long description

### Expected behavior
Asterisk has non-breaking space with last word of description

### Observed behavior
Sometimes asterisk ends up on its own on new line

### PR DESCRIPTION
**Pull request by fdlk**
For required fields, the css adds an asterisk after the label.
Use escaped unicode character because the html entities do not work inside css, see https://stackoverflow.com/questions/190396/adding-html-entities-using-css-content.

Fixes #244: Asterisk for required form sometimes ends up on separate line

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [ ] Code unit/integration/system tested
- [x] User documentation updated
- [x] Clean commits
- [x] No warnings during install
- [ ] Updated flow typing

### CODE REVIEW

File: src/formDemoMockResponse.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ const metadata = {
       'href': '/api/v2/it_emx_datatypes_TypeTest/meta/integer',
       'fieldType': 'INT',
       'name': 'integer',
-      'label': 'Integer Field',
+      'label': 'Integer Field with rather long description so we can see it wrap',
```
Comment (ConnorStroomberg) [inline src/formDemoMockResponse.js]: To test this i need a long word instead of a long sentence.

Comment (ConnorStroomberg) [reply src/formDemoMockResponse.js]: When i test using a long word at the end of the sentence i think i actually prefer the wrap.

File: src/components/FormFieldComponent.vue [hunk 2]
```diff
@@ -137,7 +137,7 @@
 
 <style>
   fieldset.required-field > div > div.form-group > label::after {
-    content: ' *';
+    content: '\a0*';
```
Comment (ConnorStroomberg) [inline src/components/FormFieldComponent.vue]: I would suggest adding the comment in what '\a0' means and why it is use there.
The comments in the mentioned stackoverflow post mention some issue with the above fix, did you take these into account ?

Comment (fdlk) [reply src/components/FormFieldComponent.vue]: Done.
Taken a closer look at the comments, not relevant here.

File: src/formDemoMockResponse.js (hunk 1 above)
Comment (fdlk) [reply src/formDemoMockResponse.js]: Updated the text to add a long word at the end.
A single asterisk on a new line on its own below the label looks a little lost and out of context to me.
