### PR TITLE
Fix #58 Required function for compound-string field does not work

### LINKED ISSUE #58: Required function for compound-string field does not work

### PR DESCRIPTION
**Pull request by Mark-de-Haan**
Replaced the methods isRequired, validate, and isVisible inside the FormFieldComponent with computed properties.

This gives the added benefit of:
1) preventing functions being called many times
2) works if the state is dependant on another field
3) properly show / hide asterisk for required fields
4) only re-run the function when the data involved changes

### CODE REVIEW

File: src/components/FormFieldComponent.vue [hunk 1]
```diff
@@ -152,26 +153,44 @@
...
       onDataChange () {
         this.$emit('dataChange')
-      },
-      // Can return more than only a boolean because of internationalized messages
-      validate () {
+      }
+    },
+    computed: {
+      /*
+       * Compute visibility to:
```
Comment (ConnorStroomberg) [inline src/components/FormFieldComponent.vue]: copy paste error , this is not the 'visibility' comment, i suggest we remove these comments ( they are more relevant for the PR), as this is default working of vue
